name: Deploy to VPS

on:
  push:
    branches:
      - main


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
	  - name: Setup SSH passphrase
        env:
        SSH_PASSPHRASE: ${{secrets.VPS_PASSWORD}}
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      run: |
	  	eval `ssh-agent -s`
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/solbubbles-landing
            ./scripts/deploy.sh
